import type { Config } from 'tailwindcss'

export default {
  content: [
    './components/**/*.{js,vue,ts}',
    './layouts/**/*.vue',
    './pages/**/*.vue',
    './plugins/**/*.{js,ts}',
    './app.vue',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#a04100',
        'primary-container': '#ff6b00',
        'on-primary': '#ffffff',
        'on-primary-container': '#572000',
        'primary-fixed': '#ffdbcc',
        secondary: '#705d00',
        'secondary-container': '#fdd73b',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#715d00',
        'secondary-fixed': '#ffe173',
        tertiary: '#ba1a25',
        'tertiary-container': '#ff6763',
        error: '#ba1a1a',
        background: '#fcf9f4',
        surface: '#fcf9f4',
        'surface-container': '#f0ede9',
        'surface-container-low': '#f6f3ee',
        'surface-container-high': '#ebe8e3',
        'surface-container-highest': '#e5e2dd',
        'on-background': '#1c1c19',
        'on-surface': '#1c1c19',
        'on-surface-variant': '#5a4136',
        outline: '#8e7164',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Be Vietnam Pro', 'sans-serif'],
        label: ['Plus Jakarta Sans', 'sans-serif'],
      },
      borderRadius: {
        'sm': '0.25rem',
        'DEFAULT': '0.5rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
        '2xl': '2rem',
        '3xl': '3rem',
      },
    },
  },
  plugins: [],
} satisfies Config