// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/2/2026, 10:31:24 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/wmt/.qclaw/workspace-agent-053539cb/meal-planner/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/wmt/.qclaw/workspace-agent-053539cb/meal-planner/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/wmt/.qclaw/workspace-agent-053539cb/meal-planner/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/wmt/.qclaw/workspace-agent-053539cb/meal-planner/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/wmt/.qclaw/workspace-agent-053539cb/meal-planner/plugins/**/*.{js,ts,mjs}","/Users/wmt/.qclaw/workspace-agent-053539cb/meal-planner/composables/**/*.{js,ts,mjs}","/Users/wmt/.qclaw/workspace-agent-053539cb/meal-planner/utils/**/*.{js,ts,mjs}","/Users/wmt/.qclaw/workspace-agent-053539cb/meal-planner/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/wmt/.qclaw/workspace-agent-053539cb/meal-planner/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/wmt/.qclaw/workspace-agent-053539cb/meal-planner/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/wmt/.qclaw/workspace-agent-053539cb/meal-planner/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;